[INCPP122DG-167] Refactor OpenId Lib
Wealize/openid_lib pull request #10
Opened 2024-08-20 14:38 UTC by FlorentinPG

## Description
The code has been refactor to reduce the amount of callbacks needed to use the code. In order to so, the library now handle an internal state through a key-value interface. This means that the amount of required data from a integrator is reduced. Due to theses changes, the complexity of the building phase of a RP object has increased, so to mitigate that, a step builder has been created.

Also, for the VC Issuer a new component has been established. This is the CredentialDataManager which responsability is to give the VC Issuer all the data related to VC, this means credential subject data but also Credential Status and terms of use. This component must be also implemented by the user.

## What type of PR is this? (check all applicable)

- [X] 🍕 Feature
- [ ] 🐛 Bug Fix
- [X] 📝 Documentation Update
- [ ] 🎨 Style
- [X] 🧑‍💻 Code Refactor
- [ ] 🔥 Performance Improvements
- [X] ✅ Test
- [ ] 🤖 Build
- [ ] 🔁 CI
- [ ] 📦 Chore (Release)
- [ ] ⏩ Revert

## Related Tickets & Documents
[INCPP122DG-167](https://wealize.atlassian.net/browse/INCPP122DG-167)

## Added tests?

- [X] 👍 yes
- [ ] 🙅 no, because they aren't needed
- [ ] 🙋 no, because I need help

## Added to documentation?

- [X] 📜 README.md
- [X] 📓 docs in project
- [ ] 🍕 Shared with team / daily
- [ ] 🙅 no documentation needed

## [optional] Are there any post-deployment tasks we need to perform?

2024-10-03 11:44 UTC, yerayrodriguez commented on src/common/classes/result.ts
> +export class Result<S extends unknown, E extends Error | unknown> {
Tenemos que hacer una valoración de librerías de este tipo, yo ya tenía varias localizadas, a ver si busco un hueco.

2024-10-03 11:45 UTC, yerayrodriguez commented on src/common/types/index.ts
> +export type VerificationResult = { valid: boolean, error?: string }; // TODO: DELETE IT
en el TODO, pon algo de contexto, si no solo tu sabes el motivo, y e incluso tu en un tiempo podrías no saber el motivo.

2024-10-03 11:50 UTC, yerayrodriguez commented on src/common/utils/array.utils.ts
> +export function arraysAreEqual(arr1: any[], arr2: any[]): boolean {
Mira la solución 1 de https://flexiple.com/javascript/javascript-array-equality
a ver qe te parece.

2024-10-03 11:53 UTC, yerayrodriguez commented on src/core/credentials/types.ts
> +  | InTimeCredentialData
La primera barra aporta algo?

2024-10-03 12:13 UTC, yerayrodriguez commented on src/core/credentials/types.ts
> +  type: "InTime",
He visto que esto lo pones para hacer un pattern matching. me resulta super curioso que el match sea capaz de resolver que type existe en los 2 tipos posibles sin dar error (vc_issuer.ts). Yo si lo tuviera que implementar hubiera creado una interfaz común, tipo hasType, y estas dos extenderían de esa. Así me aseguro que el compilador sabe que tienen esa propiedad encomún.

2024-10-03 12:20 UTC, yerayrodriguez commented on src/core/credentials/credential_data_manager.ts
> +export abstract class CredentialDataManager {
te pongo el comentario aquí, pero en general me entran dudas del alcance de la librería, no por si está bien o no lo que hace, sino por si debería hacer muchas de las cosas que hace.
A ver si me explico. El objetivo de la librería es implementar OpenID. Y yo entiendo esto como las comunicaciones entre las dos partes. Ahora bien, la generación en sí de la credencial no tengo claro que deba ser responsabilidad de esta librería. Simplemente una reflexión a tener en cuenta que podemos discutir mas adelante

2024-10-03 12:30 UTC, yerayrodriguez requested changes
Algunos comentarios menores. Mi mayor preocupación es lo del alcance de la librería, pero no es algo que vayamos a resolver en esta PR. No te la apruebo simplemente por lo de localizar el bug que estuvimos viendo

2024-10-21 13:37 UTC, FlorentinPG commented on src/core/credentials/types.ts
> +  | InTimeCredentialData
Nada

2024-10-21 13:37 UTC, FlorentinPG commented on src/common/utils/array.utils.ts
> +export function arraysAreEqual(arr1: any[], arr2: any[]): boolean {
Definitivamente más elegante

2024-10-21 14:19 UTC, yerayrodriguez approved these changes

2024-10-21 15:54 UTC, merged