[INCPP122DG-267] Fix Schema resolution
Wealize/openid_lib pull request #11
Opened 2024-09-25 14:41 UTC by FlorentinPG

## Description
Se modifica la librería que se utiliza para validar los JSON Schema de las credenciales con objeto de resolver un problema de resolución interna de referencias y también la obtención de esquemas remotos.

## What type of PR is this? (check all applicable)

- [ ] 🍕 Feature
- [X] 🐛 Bug Fix
- [ ] 📝 Documentation Update
- [ ] 🎨 Style
- [ ] 🧑‍💻 Code Refactor
- [ ] 🔥 Performance Improvements
- [ ] ✅ Test
- [ ] 🤖 Build
- [ ] 🔁 CI
- [ ] 📦 Chore (Release)
- [ ] ⏩ Revert

## Related Tickets & Documents
[INCPP122DG-267](https://wealize.atlassian.net/browse/INCPP122DG-267)

## Added tests?

- [ ] 👍 yes
- [x] 🙅 no, because they aren't needed
- [ ] 🙋 no, because I need help

## Added to documentation?

- [ ] 📜 README.md
- [ ] 📓 docs in project
- [ ] 🍕 Shared with team / daily
- [x] 🙅 no documentation needed

## [optional] Are there any post-deployment tasks we need to perform?

2024-09-25 15:13 UTC, yerayrodriguez requested changes

2024-09-25 15:13 UTC, yerayrodriguez commented on package.json
No has eliminado la dependencia antigua a jsonschema

2024-09-25 15:13 UTC, yerayrodriguez commented on src/core/presentations/vp-resolver.ts
>  } from "jsonschema";
No has eliminado la dependencia con jsonschema

2024-09-25 15:13 UTC, yerayrodriguez commented on src/core/presentations/vp-resolver.ts
>  } from "jsonschema";
Mirando el código de este fichero, simplemente usas Schema para una conversión de tipo

2024-10-02 11:01 UTC, FlorentinPG commented on package.json
Hecho

2024-10-02 11:01 UTC, FlorentinPG commented on src/core/presentations/vp-resolver.ts
>  } from "jsonschema";
Quitado Schema

2024-10-02 11:49 UTC, yerayrodriguez approved these changes

2024-10-04 08:22 UTC, merged