[PER-123] Update to Node22
Wealize/openid_lib pull request #13
Opened 2024-11-27 15:29 UTC by FlorentinPG

## Description
Se actualiza la librería para que emplee node 22 y, además, se cambia el estilo del código para que coincida con las indicaciones de Google. 

## What type of PR is this? (check all applicable)

- [X] 🍕 Feature
- [ ] 🐛 Bug Fix
- [ ] 📝 Documentation Update
- [X] 🎨 Style
- [ ] 🧑‍💻 Code Refactor
- [ ] 🔥 Performance Improvements
- [ ] ✅ Test
- [ ] 🤖 Build
- [ ] 🔁 CI
- [ ] 📦 Chore (Release)
- [ ] ⏩ Revert

## Related Tickets & Documents
[PER-123](https://wealize.atlassian.net/browse/PER-123)

## Added tests?

- [x] 👍 yes
- [ ] 🙅 no, because they aren't needed
- [ ] 🙋 no, because I need help

## Added to documentation?

- [ ] 📜 README.md
- [ ] 📓 docs in project
- [ ] 🍕 Shared with team / daily
- [ ] 🙅 no documentation needed

## [optional] Are there any post-deployment tasks we need to perform?

2024-11-27 18:10 UTC, yerayrodriguez requested changes
Una última cosa, entiendo que no vas a hacer merge con develop hasta que lo pruebes con el vc service no? lo digo por si acaso, ya que el vc-service tira de la rama develop

2024-11-27 18:10 UTC, yerayrodriguez commented on .eslintrc.json
> +    "@typescript-eslint/no-explicit-any": "off",
Lo que hablamos, si se da en pocos sitios, valoraría quitar la regla y añadirlas en las líneas donde pase.

2024-11-27 18:10 UTC, yerayrodriguez commented on .vscode/launch.json
> +      "name": "App",
Esta opción de configuración creo que no tiene sentido en este caso al ser una librería. Entiendo que no hay un punto de entrada que puedas ejecutar como tal, es decir, no hay un npm start

2024-11-27 18:10 UTC, yerayrodriguez commented on package.json
> +    "copy-files": "copyfiles -u 1 src/**/*.yaml src/**/*.json src/**/*.js dist/src/",
este comando revísalo. En la plantilla que te pasé se copian varias cosas pq hace falta, por ejemplo los openapi, o en el caso de ejemplo, había plantillas js. En tu caso creo que te sobra. Si no tienes que copiar nada te sobraría el comando entero y tendrías que cambiar el comando compile

2024-11-27 18:10 UTC, yerayrodriguez commented on dist/jest.config.d.ts
> +import type { JestConfigWithTsJest } from 'ts-jest';
Esto no lo había pensado, en dist se están metiendo los tests, pero realmente no los necesitamos. No se si deberíamos meterlos o no, tu que opinas? he visto esto
https://stackoverflow.com/a/74189761

2024-11-27 18:10 UTC, yerayrodriguez commented on dist/jest.config.d.ts
> +import type { JestConfigWithTsJest } from 'ts-jest';
bueno, viendo mejor el resto, los tests no se están incluyendo, solo los ficheros de configuración de jest. Lo hablamos

2024-11-27 18:10 UTC, yerayrodriguez commented on test/metadata.spec.ts
> +// import { expect } from "chai";
borrar

2024-11-27 18:10 UTC, yerayrodriguez commented on test/rp.spec.ts
> +// import { assert, expect } from "chai";
borrar

2024-11-27 18:10 UTC, yerayrodriguez commented on test/rp.spec.ts
> +          await generateChallenge("test"),
esto está bien?

2024-11-27 18:10 UTC, yerayrodriguez commented on tsconfig.json
> +    "old/**"
esto es de una prueba tal vez?

2025-01-13 09:34 UTC, FlorentinPG commented on dist/jest.config.d.ts
> +import type { JestConfigWithTsJest } from 'ts-jest';
Los he quitado de dist ahora

2025-01-13 09:56 UTC, FlorentinPG commented on test/rp.spec.ts
> +          await generateChallenge("test"),
Sí, está bien. Antes el test se estaba haciendo con el valor correcto y este en concreto tiene que fallar.

2025-01-13 09:56 UTC, FlorentinPG commented on tsconfig.json
> +    "old/**"
Sí

2025-01-13 10:04 UTC, yerayrodriguez approved these changes

2025-01-13 16:23 UTC, merged