[EBSIVECTOR-113] VC Identifiers and suport for short lived VCs
Wealize/openid_lib pull request #6
Opened 2024-04-30 16:41 UTC by FlorentinPG

## Description
Changed the ID of the issued VC to urn:uuid:{uuidv4 Identifier} and added support fot the user to specify the iat and nbf of a VC.

## What type of PR is this? (check all applicable)

- [x] 🍕 Feature
- [ ] 🐛 Bug Fix
- [ ] 📝 Documentation Update
- [ ] 🎨 Style
- [ ] 🧑‍💻 Code Refactor
- [ ] 🔥 Performance Improvements
- [ ] ✅ Test
- [ ] 🤖 Build
- [ ] 🔁 CI
- [ ] 📦 Chore (Release)
- [ ] ⏩ Revert

## Related Tickets & Documents

## Added tests?

- [ ] 👍 yes
- [X] 🙅 no, because they aren't needed
- [ ] 🙋 no, because I need help

## Added to documentation?

- [ ] 📜 README.md
- [ ] 📓 docs in project
- [ ] 🍕 Shared with team / daily
- [X] 🙅 no documentation needed

## [optional] Are there any post-deployment tasks we need to perform?

  

[EBSIVECTOR-113]: https://wealize.atlassian.net/browse/EBSIVECTOR-113?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

2024-05-07 09:40 UTC, yerayrodriguez requested changes

2024-05-07 09:40 UTC, yerayrodriguez commented on src/core/credentials/types.ts
> +  expiresIn?: number,
Dejar claras las unidades. O lo llamamos expiresInSecs, o al menos en la ayuda ponerlo. Yo le cambiaría el nombre

2024-05-07 09:40 UTC, yerayrodriguez commented on src/core/credentials/types.ts
> +  /** The expiration time in UTC and in ISO string format. Can't be combined with expiresIn */
ISO string representa un momento que se puede expresar con o sin indicativo de Zulu, y con o sin offset. Si no tiene la Z o el offset representa zona horaria local. Creo que es así. Esto te lo cuento pq si este valor nos viene de fuera, puede que no represente UTC directamente. Tal vez habría que hacerle algún procesado para garantizar que sea así y evitar errores. Imagina que alguien nos manda este valor sin la z, representando su zona local, y nosotros tenemos el servidor en otra zona local. Yo obligaría a que lo indicara. En JS podemos utilizar momment.js. No se cual sería la complejidad por lo de las serializaciones y desserializaciones, pero tal vez deberíamos tener un tipo de dato que fuera datetime. Lo hablamos si quieres.

2024-05-07 09:40 UTC, yerayrodriguez commented on src/core/credentials/types.ts
> +  // getValidUntil?: (types: string[]) => Promise<string>;
por qué está comentado? es por lo del código que dijimos de dejar temporalmente fuera?

2024-05-07 09:40 UTC, yerayrodriguez commented on src/core/credentials/vc_issuer.ts
> +        `"expiresIn paramater and "validUntil" parameter can't be provided at the same time"`
es una bobería, pero las comillas no son consistentes en el mensaje

2024-05-07 09:40 UTC, yerayrodriguez commented on src/core/credentials/vc_issuer.ts
> +    if (data.expiresIn && expirationDate) {
este if es un poco raro, deberías poner al principio del método algo tipo if data.validUntil && data.expiresIn -> Error

2024-05-07 09:40 UTC, yerayrodriguez commented on src/core/credentials/vc_issuer.ts
> +    const vcId = `urn:uuid:${uuidv4()}`;
crea un método para la generación del vcId, que veo que abajo está repetido

2024-05-08 14:43 UTC, FlorentinPG commented on src/core/credentials/types.ts
> +  /** The expiration time in UTC and in ISO string format. Can't be combined with expiresIn */
Me parece bien lo que planteas lo de hacer la comprobación porque es cierto que puede pasar que nos envíen cualquier cosa, incluso cuestiones que no sean fechas, y no generen ningún error. Hay un TODO de hecho de dedicar tiempo a crear esquemas para utilizarlos para verificarlos los datos entrantes.

2024-05-08 14:44 UTC, FlorentinPG commented on src/core/credentials/types.ts
> +  // getValidUntil?: (types: string[]) => Promise<string>;
Está comentado porque ya no se usaría por el tema de las VCs de corta duración. Antes para especificar el tiempo se usaba un parámetro opcional del método, pero el problema está en que entonces se debería conocer el tiempo de validez de la VCs antes de llamar al método, y con el enfoque dinámico esto no es posible. En cuanto las VCs de corta duración estén soportadas eliminaré el comentario.

2024-05-20 09:48 UTC, yerayrodriguez requested changes

2024-05-20 09:48 UTC, yerayrodriguez commented on src/core/credentials/vc_issuer.ts
> +      now: new Date(now).toISOString(),
te recomendaría cambiar el nombre, de now, a algo tipo iss, o issuance, o issuanceDate, o algo similar. now es un poco confuso cuando sales del contexto de esta función

2024-05-20 09:48 UTC, yerayrodriguez commented on src/core/credentials/vc_issuer.ts
> +      validFrom: timestamps.nbf ?? timestamps.now,
validfrom es de v1?

2024-05-21 07:39 UTC, FlorentinPG commented on src/core/credentials/vc_issuer.ts
> +      validFrom: timestamps.nbf ?? timestamps.now,
La añade como palabra reservada

2024-05-21 08:53 UTC, yerayrodriguez approved these changes

2024-05-21 09:33 UTC, merged